<?php

namespace Louvre\FrontBundle\Repository;

/**
 * BillingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillingRepository extends \Doctrine\ORM\EntityRepository
{
}
