<?php

namespace Louvre\FrontBundle\Repository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $visit_date
     * @param $numberTickets
     * @return int
     */
    public function countTicketsByDay($visit_date)
    {
        $countTicket = $this->getEntityManager()->createQueryBuilder()
            ->select("count(o.id)")
            ->from("LouvreFrontBundle:Order", "o")
            ->leftJoin("o.tickets","t")
            ->where("o.visitDate = :visit_date")
            ->setParameter('visit_date', $visit_date)
            ->getQuery();

        return intval($countTicket->getSingleScalarResult());
    }


}
