<?php

namespace Louvre\FrontBundle\Repository;

/**
 * ticketsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ticketsRepository extends \Doctrine\ORM\EntityRepository
{
}
