# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  alaczi.twig.country_extension:
    class: alaczi\Twig\Extension\CountryExtension
    tags:
        - { name: twig.extension }