louvre_front_homepage:
    path:     /
    defaults: { _controller: LouvreFrontBundle:Default:index }

louvre_front_reservation:
    path:     /addBooking
    defaults: { _controller: LouvreFrontBundle:Booking:addBooking }
