louvre_front_homepage:
    path:     /
    defaults: { _controller: LouvreFrontBundle:Default:index }

louvre_front_horaires:
    path:     /horaires
    defaults: { _controller: LouvreFrontBundle:Default:horaires }

louvre_front_mentions_legales:
    path:     /mentions_legales
    defaults: { _controller: LouvreFrontBundle:Default:mentionsLegales }

louvre_front_contact:
    path:     /contact
    defaults: { _controller: LouvreFrontBundle:Default:contact }

louvre_front_showorder:
    path:     /order/
    defaults: { _controller: LouvreFrontBundle:Booking/ShowBooking:showOrder}
    methods: [GET]

louvre_front_saveorder:
    path:     /order/save
    defaults: { _controller: LouvreFrontBundle:Booking/SaveBooking:saveOrder}
    methods: [POST]

louvre_front_prepare_order:
    path:     /order/prepare
    defaults: { _controller: LouvreFrontBundle:Payments/Payments:confirmOrderForm}
    methods: [POST]

louvre_front_confirmed_order:
    path:     /order/confirmed
    defaults: { _controller: LouvreFrontBundle:Payments/Payments:confirmPayement}
    methods: [GET, POST]