services:
    louvre.front_bundle.form.orders_type:
        class: Louvre\FrontBundle\Form\OrdersType
        calls:
            - method: setRouter
              arguments:
                - '@router'
        tags:
            - {name: form.type}
