services:
    Louvre.twig_session:
        class: Louvre\FrontBundle\Twig\Extension\TwigSession
        public: false
        tags:
            - { name: twig.extension }

    louvre.front_bundle.form.orders_type:
        class: Louvre\FrontBundle\Form\OrderType
        calls:
            - method: setRouter
              arguments:
                - '@router'
        tags:
            - {name: form.type}

    louvre.front_bundle.entity.order_factory:
        class: Louvre\FrontBundle\Entity\OrderFactory
        calls:
            - method: setTicketFactory
              arguments:
                - '@louvre.front_bundle.entity.ticket_factory'

    louvre.front_bundle.entity.ticket_factory:
            class: Louvre\FrontBundle\Entity\TicketFactory

    louvre.front_bundle.repository.order_repository:
        class: Louvre\FrontBundle\Repository\OrderRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
                - Louvre\FrontBundle\Entity\Order

    louvre_front.controller_payments.payments_prepare_order:
        class: Louvre\FrontBundle\Controller\Payments\PaymentsController
        calls:
            - [confirmOrderFormAction, ['@?']]
            - [setContainer, ['@service_container']]

    louvre_front.controller_payments.payments_form:
        class: Louvre\FrontBundle\Controller\Payments\PaymentsController
        calls:
            - [showPaymentFormAction, ['@?']]
            - [setContainer, ['@service_container']]

    louvre_front.controller.save_afert_payement_controller:
        class: Louvre\FrontBundle\Controller\Payments\SaveAfertPayementController
        calls:
            - [saveOrderInBaseAction, ['@?']]

