services:

    louvre.front_bundle.form.orders_type:
        class: Louvre\FrontBundle\Form\OrderType
        calls:
            - method: setRouter
              arguments:
                - '@router'
        tags:
            - {name: form.type}

    louvre.front_bundle.entity.order_factory:
        class: Louvre\FrontBundle\Entity\OrderFactory
        calls:
            - method: setTicketFactory
              arguments:
                - '@louvre.front_bundle.entity.ticket_factory'

    louvre.front_bundle.entity.ticket_factory:
            class: Louvre\FrontBundle\Entity\TicketFactory

    louvre.front_bundle.repository.order_repository:
        class: Louvre\FrontBundle\Repository\OrderRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
                - Louvre\FrontBundle\Entity\Order

    louvre_front.services.send_tickets_by_email:
        class: Louvre\FrontBundle\Services\MailManager
        arguments: ['@templating.engine.twig', '@swiftmailer.mailer']
        calls:
            - [sendCommandMail, ['@?']]


